<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\PolicyEngine.Domain\PolicyEngine.Domain.csproj" />
    <ProjectReference Include="..\PolicyEngine.Infrastructure\PolicyEngine.Infrastructure.csproj" />
  </ItemGroup>
</Project>
